name: Sync pr's branches with their base branch

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    name: Update branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Merge base branch
        uses: omaresmael/merge-base-branch@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
