name: Update Branches

on:
  push:
    branches:
      - master

jobs:
  update-branches:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch names
        id: branches
        run: |
          git ls-remote --heads origin | awk -F'/' '{print $3}' | grep -vE 'master$' > ${{ github.workspace }}/branches.txt

      - name: Update branches
        run: |   
          git config --global user.email "sigrtmax42@gmail.com"
          git config --global user.name "sigrtmax"
          while read -r branch; do
            git checkout $branch
            if ! git merge origin/master --no-edit; then
              echo "Conflict in ${branch}"
              git merge --abort
            else
              git push origin $branch
            fi
          done < ${{ github.workspace }}/branches.txt
